---
- hosts: project          # tag_ACS730
  gather_facts: True
  become: yes
  
  vars:
    ansible_user: ec2-user
    ansible_private_key_file: /home/ec2-user/.ssh/project
    source_file: ./index.html
    dest_file: /var/www/html
    
    
- name: GET image
  amazon.aws.s3_object:
    bucket: acs730-project-bucket
    object: /Pictures/Hummingbird.webp  # CHANGE
    dest: /home/ec2-user/environment/ansible
    mode: get
